In [199]:
import pandas as pd

# Data Cleaning

In [226]:
train_transaction_orig = pd.read_csv('train_transaction.csv')

In [227]:
train_transaction = train_transaction_orig.copy()

In [228]:
train_transaction.head()

,TransactionID,isFraud,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,...,V330,V331,V332,V333,V334,V335,V336,V337,V338,V339
0,2987000,0,86400,68.5,W,13926,NaN,150.0,discover,142.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2987001,0,86401,29.0,W,2755,404.0,150.0,mastercard,102.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2987002,0,86469,59.0,W,4663,490.0,150.0,visa,166.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2987003,0,86499,50.0,W,18132,567.0,150.0,mastercard,117.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2987004,0,86506,50.0,H,4497,514.0,150.0,mastercard,102.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [229]:
pd.Series(train_transaction.columns)

0       TransactionID
1             isFraud
2       TransactionDT
3      TransactionAmt
4           ProductCD
5               card1
6               card2
7               card3
8               card4
9               card5
10              card6
11              addr1
12              addr2
13              dist1
14              dist2
15      P_emaildomain
16      R_emaildomain
17                 C1
18                 C2
19                 C3
20                 C4
21                 C5
22                 C6
23                 C7
24                 C8
25                 C9
26                C10
27                C11
28                C12
29                C13
            ...
364              V310
365              V311
366              V312
367              V313
368              V314
369              V315
370              V316
371              V317
372              V318
373              V319
374              V320
375              V321
376              V322
377              V323
378              V324
379              V325
380              V326
381              V327
382              V328
383              V329
384              V330
385              V331
386              V332
387              V333
388              V334
389              V335
390              V336
391              V337
392              V338
393              V339
Length: 394, dtype: object

In [230]:
train_transaction['P_emaildomain'].value_counts(dropna=False)

gmail.com           228355
yahoo.com           100934
NaN                  94456
hotmail.com          45250
anonymous.com        36998
aol.com              28289
comcast.net           7888
icloud.com            6267
outlook.com           5096
msn.com               4092
att.net               4033
live.com              3041
sbcglobal.net         2970
verizon.net           2705
ymail.com             2396
bellsouth.net         1909
yahoo.com.mx          1543
me.com                1522
cox.net               1393
optonline.net         1011
charter.net            816
live.com.mx            749
rocketmail.com         664
mail.com               559
earthlink.net          514
gmail                  496
outlook.es             438
mac.com                436
juno.com               322
aim.com                315
hotmail.es             305
windstream.net         305
roadrunner.com         305
hotmail.fr             295
frontier.com           280
embarqmail.com         260
web.de                 240
twc.com                230
netzero.com            230
prodigy.net.mx         207
centurylink.net        205
netzero.net            196
frontiernet.net        195
q.com                  189
suddenlink.net         175
cfl.rr.com             172
sc.rr.com              164
cableone.net           159
gmx.de                 149
yahoo.fr               143
yahoo.es               134
hotmail.co.uk          112
protonmail.com          76
yahoo.de                74
ptd.net                 68
live.fr                 56
yahoo.co.uk             49
hotmail.de              43
servicios-ta.com        35
yahoo.co.jp             32
Name: P_emaildomain, dtype: int64

In [231]:
train_transaction['P_emaildomain'].fillna('Unknown purchaser email address', inplace = True)
train_transaction['P_emaildomain'].value_counts(dropna=False)

gmail.com                          228355
yahoo.com                          100934
Unknown purchaser email address     94456
hotmail.com                         45250
anonymous.com                       36998
aol.com                             28289
comcast.net                          7888
icloud.com                           6267
outlook.com                          5096
msn.com                              4092
att.net                              4033
live.com                             3041
sbcglobal.net                        2970
verizon.net                          2705
ymail.com                            2396
bellsouth.net                        1909
yahoo.com.mx                         1543
me.com                               1522
cox.net                              1393
optonline.net                        1011
charter.net                           816
live.com.mx                           749
rocketmail.com                        664
mail.com                              559
earthlink.net                         514
gmail                                 496
outlook.es                            438
mac.com                               436
juno.com                              322
aim.com                               315
hotmail.es                            305
windstream.net                        305
roadrunner.com                        305
hotmail.fr                            295
frontier.com                          280
embarqmail.com                        260
web.de                                240
twc.com                               230
netzero.com                           230
prodigy.net.mx                        207
centurylink.net                       205
netzero.net                           196
frontiernet.net                       195
q.com                                 189
suddenlink.net                        175
cfl.rr.com                            172
sc.rr.com                             164
cableone.net                          159
gmx.de                                149
yahoo.fr                              143
yahoo.es                              134
hotmail.co.uk                         112
protonmail.com                         76
yahoo.de                               74
ptd.net                                68
live.fr                                56
yahoo.co.uk                            49
hotmail.de                             43
servicios-ta.com                       35
yahoo.co.jp                            32
Name: P_emaildomain, dtype: int64

In [232]:
train_transaction['R_emaildomain'].value_counts(dropna=False)

NaN                 453249
gmail.com            57147
hotmail.com          27509
anonymous.com        20529
yahoo.com            11842
aol.com               3701
outlook.com           2507
comcast.net           1812
yahoo.com.mx          1508
icloud.com            1398
msn.com                852
live.com               762
live.com.mx            754
verizon.net            620
me.com                 556
sbcglobal.net          552
cox.net                459
outlook.es             433
att.net                430
bellsouth.net          422
hotmail.fr             293
hotmail.es             292
web.de                 237
mac.com                218
ymail.com              207
prodigy.net.mx         207
optonline.net          187
gmx.de                 147
yahoo.fr               137
charter.net            127
                     ...
hotmail.co.uk          105
gmail                   95
earthlink.net           79
yahoo.de                75
rocketmail.com          69
embarqmail.com          68
scranton.edu            63
yahoo.es                57
live.fr                 55
juno.com                53
roadrunner.com          53
frontier.com            52
windstream.net          47
hotmail.de              42
protonmail.com          41
yahoo.co.uk             39
cfl.rr.com              37
aim.com                 36
servicios-ta.com        35
yahoo.co.jp             33
twc.com                 29
cableone.net            27
ptd.net                 27
q.com                   25
suddenlink.net          25
frontiernet.net         14
netzero.com             14
centurylink.net         12
netzero.net              9
sc.rr.com                8
Name: R_emaildomain, Length: 61, dtype: int64

In [233]:
train_transaction['R_emaildomain'].fillna('Unknown receiver email address', inplace = True)
train_transaction['R_emaildomain'].value_counts(dropna=False)

Unknown receiver email address    453249
gmail.com                          57147
hotmail.com                        27509
anonymous.com                      20529
yahoo.com                          11842
aol.com                             3701
outlook.com                         2507
comcast.net                         1812
yahoo.com.mx                        1508
icloud.com                          1398
msn.com                              852
live.com                             762
live.com.mx                          754
verizon.net                          620
me.com                               556
sbcglobal.net                        552
cox.net                              459
outlook.es                           433
att.net                              430
bellsouth.net                        422
hotmail.fr                           293
hotmail.es                           292
web.de                               237
mac.com                              218
ymail.com                            207
prodigy.net.mx                       207
optonline.net                        187
gmx.de                               147
yahoo.fr                             137
charter.net                          127
                                   ...
hotmail.co.uk                        105
gmail                                 95
earthlink.net                         79
yahoo.de                              75
rocketmail.com                        69
embarqmail.com                        68
scranton.edu                          63
yahoo.es                              57
live.fr                               55
juno.com                              53
roadrunner.com                        53
frontier.com                          52
windstream.net                        47
hotmail.de                            42
protonmail.com                        41
yahoo.co.uk                           39
cfl.rr.com                            37
aim.com                               36
servicios-ta.com                      35
yahoo.co.jp                           33
twc.com                               29
cableone.net                          27
ptd.net                               27
q.com                                 25
suddenlink.net                        25
netzero.com                           14
frontiernet.net                       14
centurylink.net                       12
netzero.net                            9
sc.rr.com                              8
Name: R_emaildomain, Length: 61, dtype: int64

In [234]:
M_SERIES = ['M1', 'M2', 'M3', 'M4', 'M5', 'M6', 'M7', 'M8', 'M9', 'addr1', 'addr2', 'card1', 'card2', 'card3', 'card4', 'card5', 'card6' ]

In [235]:
def fill_missing_value_categorical(col, df):
    sorted_column = df[col].value_counts()
    df[col].fillna(sorted_column.index[0], inplace=True)

In [237]:
[fill_missing_value_categorical(value, train_transaction) for value in M_SERIES]

[None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None]

In [238]:
train_transaction['M9'].value_counts(dropna=False)

T    551908
F     38632
Name: M9, dtype: int64

In [239]:
train_transaction.ProductCD.notnull().all()

True

In [240]:
V_SERIES = ['V' + str(i) for i in range(1, 340)]
Other = ['dist1', 'dist2']
D_SERIES = ['D' + str(i) for i in range(1, 16)]
C_SERIES = ['C' + str(i) for i in range(1, 15)]

In [241]:
features = []
features.extend(V_SERIES)
features.extend(Other)
features.extend(D_SERIES)
features.extend(C_SERIES)

In [242]:
len(features)

370

In [243]:
def fill_missing_value_numeric(col, df):
    mean_value = df[col].mean()
    df[col].fillna(mean_value, inplace=True)

In [244]:
[fill_missing_value_numeric(value, train_transaction) for value in features]

[None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None]

In [245]:
train_transaction.notnull().all().all()

True

In [246]:
train_identity_orig = pd.read_csv('train_identity.csv')

In [247]:
train_identity = train_identity_orig.copy()

In [248]:
train_identity.columns

Index(['TransactionID', 'id_01', 'id_02', 'id_03', 'id_04', 'id_05', 'id_06',
       'id_07', 'id_08', 'id_09', 'id_10', 'id_11', 'id_12', 'id_13', 'id_14',
       'id_15', 'id_16', 'id_17', 'id_18', 'id_19', 'id_20', 'id_21', 'id_22',
       'id_23', 'id_24', 'id_25', 'id_26', 'id_27', 'id_28', 'id_29', 'id_30',
       'id_31', 'id_32', 'id_33', 'id_34', 'id_35', 'id_36', 'id_37', 'id_38',
       'DeviceType', 'DeviceInfo'],
      dtype='object')

In [225]:
categorical_featues = []
id_categorical_features = ['id_' + str(i) for i in range(12, 39)]
categorical_featues.extend(id_features)
categorical_featues.extend(['DeviceType', 'DeviceInfo'])

In [253]:
numeric_features = []
id_numeric_features_under9 = ['id_0' + str(i) for i in range(1, 10)]
numeric_features.extend(id_numeric_features_under9)
numeric_features.extend(['id_10', 'id_11'])

In [254]:
[fill_missing_value_categorical(value, train_identity) for value in categorical_featues]

[None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None]

In [255]:
[fill_missing_value_numeric(value, train_identity) for value in numeric_features]

[None, None, None, None, None, None, None, None, None, None, None]

In [257]:
train_identity.notnull().all().all()

True